defmodule Cambiatus.Repo.Migrations.CreateAuthRequests do
  use Ecto.Migration

  def change do
    create table(:auth_requests) do
      add(:user_id, references(:users, column: :account, type: :string), null: false)
      add(:phrase, :string, null: false, comment: "Autogenerated phrase")
      add(:ip_address, :string)
      add(:domain, :string, null: false)

      timestamps()
    end
  end
end
